settings: {strict: true}
input: {driver: sdata, file: inversionBACK.sdat}
output:
    segment: {function: classic, stream: bench_inversionRslts.txt}
retrieval:
    general: {path_to_internal_files: /data/home/gregmi/GRASP_V2/grasp-dev-rtm-v120-new-inter/src/retrieval/internal_files}
    mode: inversion
    inversion:
        regime: single_pixel
        convergence: {maximum_iterations_for_stopping: 20, maximum_iterations_of_Levenberg-Marquardt: 20, minimization_convention: logarithm, scale_for_finite_difference: 3.0e-05, shift_for_applying_logarithm_to_negative_values: 1.1, threshold_for_stopping: 1.0e-09, threshold_for_stopping_Q_iterations: 1.0e-10}
        measurement_fitting: {polarization: degree_of_polarization}
        noises:
            noise[1]:
                error_type: relative
                measurement_type[1]:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    type: I
                standard_deviation: 0.03
                standard_deviation_synthetic: 0.0
            noise[2]:
                error_type: absolute
                standard_deviation: 0.005
                measurement_type[1]:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    type: p_rel

           
    forward_model:
        phase_matrix:
            kernels_folder: KERNELS_BASE/
            size_binning_method_for_triangle_bins: logarithm
            number_of_elements: 4
            radius:
                mode[1]: {max: 16.0, min: 0.01}
                mode[2]: {max: 16.0, min: 0.01}
                mode[3]: {max: 16.0, min: 0.01}
        atmospheric_vertical_profile:
            aerosol_profile_vertical_type: gaussian
            molecular_profile_vertical_type: standard_atmosphere
            vertical_discrete_type: all_level
        radiative_transfer:
            absolute_error_rt_calculations: 1.0e-06
            number_of_layers: 50
            reference_plane_for_polarization: principal_plane
            simulating_derivatives: {number_of_fourier_expansion_coefficients: 6, number_of_gaussian_quadratures_for_expansion_coefficients: 10, number_of_guassian_quadratures_for_fourier_expansion_coefficients: 20, order_of_scattering: multiple_scattering}
            simulating_observation: {number_of_fourier_expansion_coefficients: 6, number_of_gaussian_quadratures_for_expansion_coefficients: 10, number_of_guassian_quadratures_for_fourier_expansion_coefficients: 20, order_of_scattering: multiple_scattering}
    debug: {additional_information: false, verbose: true}
    products:
        aerosol: {chemistry: false, lidar: true, optical_properties: true, phase_matrix: true, refractive_index: true, theoretical_bimodal_extinction: false, theoretical_bimodal_parameters: false}
        error_estimation:
            aerosol: {lidar: false, optical_properties: false}
            parameters: false
        forcing: {broadband_flux: false, forcing: false}
        retrieval: {fitting: true, parameters: true, residual: true}
        surface: {main_characteristics: true, isotropic_bihemispherical_reflectance: false}
    constraints:
        characteristic[1]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1]
                    min: [1.0e-08]
                    value: [0.01]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [3]
                    min: [1.0e-08]
                    value: [0.8]
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1]
                    min: [1.0e-08]
                    value: [0.05]
            retrieved: true
            type: aerosol_concentration
        characteristic[2]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [3, 0.65]
                    min: [0.08, 0.2]
                    value: [0.13, 0.4]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [8, 0.8]
                    min: [0.8, 0.35]
                    value: [4, 0.5]
            
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [5, 0.8]
                    min: [0.8, 0.3]
                    value: [2, 0.5]
            retrieved: true
            type: size_distribution_lognormal
        characteristic[3]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    max: [1.67, 1.67, 1.67, 1.67, 1.67, 1.67, 1.67, 1.67]
                    
                    min: [1.375, 1.375, 1.375, 1.375, 1.375, 1.375, 1.375]
                    value: [1.55, 1.55, 1.55, 1.55, 1.55, 1.55, 1.55]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0.03}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    max: [1.67, 1.67, 1.67, 1.67, 1.67, 1.67, 1.67, 1.67]
                    min: [1.375, 1.375, 1.375, 1.375, 1.375, 1.375, 1.375]
                    value: [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0.03}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    max: [1.55, 1.55, 1.55, 1.55, 1.55, 1.6, 1.6]
                    min: [1.375, 1.375, 1.375, 1.375, 1.375, 1.375, 1.375]
                    value: [1.375, 1.375, 1.375, 1.375, 1.375, 1.375, 1.375]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0.03}
            retrieved: true
            type: real_part_of_refractive_index_spectral_dependent
        characteristic[4]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    max: [0.008, 0.005, 0.003, 0.003, 0.003, 0.003, 0.003]
                    min: [0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002]
                    value: [0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003]
                single_pixel:
                    smoothness_constraints: {difference_order: 2, lagrange_multiplier: 0.01}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    max: [0.008, 0.005, 0.003, 0.003, 0.003, 0.003, 0.003]
                    min: [0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002]
                    value: [0.004, 0.004, 0.003, 0.003, 0.003, 0.003, 0.003]
                single_pixel:
                    smoothness_constraints: {difference_order: 2, lagrange_multiplier: 0.01}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    max: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
                    min: [0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0002]
                    value: [0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0.01}
            retrieved: true
            type: imaginary_part_of_refractive_index_spectral_dependent
        characteristic[5]:
            type: surface_water_cox_munk_iso
            retrieved: true
            mode[1]:    
                initial_guess:                       #1      #2      #3      #4      #5      #6       
                    value:                          [0.01,   0.01,   0.01,   0.005,  0.005,  0.005  ]
                    min:                            [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001 ]
                    max:                            [0.05,   0.05,   0.05,   0.05,   0.05,   0.05   ]
                    index_of_wavelength_involved:   [1,      2,      3,      4,      5,      6      ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 1.0e-3
   
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1.0]
                    min: [0.94]
                    value: [0.97]
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [0.02582]
                    min: [0.009]
                    value: [0.015]
                    
        characteristic[6]:
            type: vertical_profile_parameter_height
            retrieved: true
            mode[1]:
                initial_guess:
                    min: [1000.0]
                    max: [5000.0]
                    value: [2000.0]
                    index_of_wavelength_involved: [0]
            mode[2]:
                initial_guess:
                    min: [1200.0]
                    max: [2500.0]
                    value: [2200.0]
                    index_of_wavelength_involved: [0]
            mode[3]:
                initial_guess:
                    min: [300.0]
                    max: [1000.0]
                    value: [500.0]
                    index_of_wavelength_involved: [0]
        characteristic[7]:
            type: vertical_profile_parameter_standard_deviation
            retrieved: true
            mode[1]:
                initial_guess:
                    min: [300]
                    max: [4000.0]
                    value: [3000.0]
                    index_of_wavelength_involved: [0]
            mode[2]:
                initial_guess:
                    min: [500]
                    max: [1000.0]
                    value: [1000.0]
                    index_of_wavelength_involved: [0]
            mode[3]:
                initial_guess:
                    min: [200.0]
                    max: [500.0]
                    value: [300.0]
                    index_of_wavelength_involved: [0]
        characteristic[8]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1]
                    min: [0.9]
                    value: [0.95]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1.0e-05]
                    min: [1.0e-07]
                    value: [1.0e-06]
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1]
                    min: [0.99]
                    value: [0.99999]
            retrieved: true
            type: sphere_fraction
