settings: {strict: true}
input: {driver: sdata, file: inversionBACK.sdat}
output:
    segment: {function: classic, stream: bench_inversionRslts.txt}
retrieval:
    general: {path_to_internal_files: /data/home/gregmi/GRASP_V2/grasp-dev-rtm-v200-pgn/src/retrieval/internal_files}
    mode: inversion
    inversion:
        regime: single_pixel
        convergence: {maximum_iterations_for_stopping: 20, maximum_iterations_of_Levenberg-Marquardt: 20, minimization_convention: logarithm, scale_for_finite_difference: 3.0e-05, shift_for_applying_logarithm_to_negative_values: 1.1, threshold_for_stopping: 1.0e-09, threshold_for_stopping_Q_iterations: 1.0e-10}
        measurement_fitting: {polarization: degree_of_polarization}
        noises:
            noise[1]:
                error_type: relative
                measurement_type[1]:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5]
                    type: I
                standard_deviation: 0.03
                standard_deviation_synthetic: 0.0
            noise[2]:
                error_type: absolute
                standard_deviation: 0.003
                measurement_type[1]:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5]
                    type: p_rel

           
    forward_model:
        phase_matrix:
            kernels_folder: KERNELS_BASE/
            size_binning_method_for_triangle_bins: logarithm
            number_of_elements: 4
            radius:
                mode[1]: {max: 20.0, min: 0.05}
                mode[2]: {max: 20.0, min: 0.05}
                mode[3]: {max: 20.0, min: 0.05}
        radiative_transfer:
            absolute_error_rt_calculations: 1.0e-06
            aerosol_profile_vertical_type: gaussian
            molecular_profile_vertical_type: standard_atmosphere
            number_of_layers: 50
            reference_plane_for_polarization: meridian
            simulating_derivatives: {number_of_fourier_expansion_coefficients: 6, number_of_gaussian_quadratures_for_expansion_coefficients: 8, number_of_guassian_quadratures_for_fourier_expansion_coefficients: 15, order_of_scattering: multiple_scattering}
            simulating_observation: {number_of_fourier_expansion_coefficients: 12, number_of_gaussian_quadratures_for_expansion_coefficients: 10, number_of_guassian_quadratures_for_fourier_expansion_coefficients: 20, order_of_scattering: multiple_scattering}
    debug: {additional_information: false, verbose: true}
    products:
        aerosol: {chemistry: false, lidar: true, optical_properties: true, phase_matrix: true, refractive_index: true, theoretical_bimodal_extinction: false, theoretical_bimodal_parameters: false}
        error_estimation:
            aerosol: {lidar: false, optical_properties: false}
            parameters: false
        forcing: {broadband_flux: false, forcing: false}
        retrieval: {fitting: true, parameters: true, residual: true}
        surface: {main_characteristics: true, isotropic_bihemispherical_reflectance: false}
    constraints:
        characteristic[1]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [0.75]
                    min: [1.0e-08]
                    value: [0.0021471]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1]
                    min: [1.0e-08]
                    value: [0.6706]
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [2]
                    min: [1.0e-08]
                    value: [0.056173]
            retrieved: true
            type: aerosol_concentration
        characteristic[2]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [0.5, 0.5]
                    min: [0.08, 0.2]
                    value: [0.13, 0.36919]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [10, 0.8]
                    min: [0.8, 0.2]
                    value: [6.949, 0.45649]
            retrieved: true
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [5, 0.85]
                    min: [0.8, 0.2]
                    value: [ 1.2993, 0.64362]
            type: size_distribution_lognormal
        characteristic[3]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    max: [1.69, 1.69, 1.69, 1.69, 1.69, 1.69, 1.69, 1.69]
                    
                    min: [1.35, 1.35, 1.35, 1.35, 1.35, 1.35, 1.35]
                    value: [1.5, 1.5337, 1.5112, 1.5536, 1.55, 1.56, 1.5]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0.03}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    max: [1.69, 1.69, 1.69, 1.69, 1.69, 1.69, 1.69, 1.69]
                    min: [1.35, 1.35, 1.35, 1.35, 1.35, 1.35, 1.35]
                    value: [1.6773, 1.6444, 1.6119, 1.6037, 1.5885, 1.5885, 1.5885]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0.03}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5,6,7]
                    max: [1.55, 1.55, 1.55, 1.55, 1.55, 1.6, 1.6]
                    min: [1.33, 1.33, 1.33, 1.33, 1.33, 1.2, 1.2]
                    value: [1.3385, 1.3338, 1.33  , 1.33  , 1.332, 1.332, 1.332]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0.03}
            retrieved: true
            type: real_part_of_refractive_index_spectral_dependent
        characteristic[4]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    max: [0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025]
                    min: [1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06]
                    value: [2.3127e-04, 2.3514e-04, 2.3092e-04, 2.2966e-04, 2.3492e-04, 2.3566e-04, 2.3492e-04]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0.01}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    max: [0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025]
                    min: [0.0002, 0.0002, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001]
                    value: [1.0162e-03, 8.2101e-04, 5.1290e-04, 6.2042e-04,8.6221e-04, 8.6221e-04]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0.01}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3, 4, 5, 6, 7]
                    max: [0.002, 0.002, 0.002, 0.002, 0.002, 0.002, 0.002]
                    min: [1.0e-10, 1.0e-10, 1.0e-10, 1.0e-10, 1.0e-10, 1.0e-10, 1.0e-10]
                    value: [5.6913e-05, 5.8017e-05, 5.9088e-05, 6.0405e-05, 6.0902e-05, 6.0902e-05, 6.0902e-05]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0.01}
            retrieved: true
            type: imaginary_part_of_refractive_index_spectral_dependent
        characteristic[5]:
            type: surface_water_cox_munk_iso
            retrieved: true
            mode[1]:
                initial_guess:
                    value: [2.0e-08, 2.0e-08, 2.0e-08, 2.0e-08, 2.0e-08, 2.0e-08, 2.0e-08]
                    min: [1.0e-09, 1.0e-09, 1.0e-09, 1.0e-09, 1.0e-09, 1.0e-09, 1.0e-09]
                    max: [4.5e-05, 4.5e-05, 4.5e-05, 4.5e-05, 4.5e-05, 4.5e-05, 4.5e-05]
                    index_of_wavelength_involved: [1, 2, 3, 4, 5]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0.05}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1.0]
                    min: [0.999]
                    value: [0.9999]
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [0.2582]
                    min: [0.0143]
                    value: [0.015]
        characteristic[6]:
            type: vertical_profile_parameter_height
            retrieved: true
            mode[1]:
                initial_guess:
                    min: [1000.0]
                    max: [5000.0]
                    value: [2708.47]
                    index_of_wavelength_involved: [0]
            mode[2]:
                initial_guess:
                    min: [1200.0]
                    max: [2500.0]
                    value: [2500]
                    index_of_wavelength_involved: [0]
            mode[3]:
                initial_guess:
                    min: [300.0]
                    max: [1000.0]
                    value: [534.47]
                    index_of_wavelength_involved: [0]
        characteristic[7]:
            type: vertical_profile_parameter_standard_deviation
            retrieved: true
            mode[1]:
                initial_guess:
                    min: [300]
                    max: [4000.0]
                    value: [3137.8]
                    index_of_wavelength_involved: [0]
            mode[2]:
                initial_guess:
                    min: [500]
                    max: [1000.0]
                    value: [942.75]
                    index_of_wavelength_involved: [0]
            mode[3]:
                initial_guess:
                    min: [200.0]
                    max: [500.0]
                    value: [324.94]
                    index_of_wavelength_involved: [0]
        characteristic[8]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1]
                    min: [1.0e-07]
                    value: [0.12894]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1]
                    min: [1.0e-07]
                    value: [1.3695e-05]
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1]
                    min: [0.9]
                    value: [0.9957]
            retrieved: true
            type: sphere_fraction
