input: {driver: sdata, file: bench.sdat}
output:
    segment: {function: classic, stream: bench_inversionRslts.txt}
retrieval:
    constraints:
        characteristic[1]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1.00001]
                    min: [0.00000001]
                    value: [0.009357605939569125]
                single_pixel:
                    smoothness_constraints: {difference_order: 0, lagrange_multiplier: 0.0}
            retrieved: true
            type: aerosol_concentration    
        characteristic[2]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [10.0, 0.95]
                    min: [0.02, 0.02]
                    value: [0.18482, 0.5709795355796814]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier: [0, 0]
            retrieved: true
            type: size_distribution_lognormal
        characteristic[3]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3]
                    max: [1.65, 1.65, 1.65]
                    min: [1.33, 1.33, 1.33]
                    value: [1.36387, 1.35939, 1.35939]
                multi_pixel:
                    smoothness_constraints: {derivative_order_of_T_variability: 1, derivative_order_of_X_variability: 1, derivative_order_of_Y_variability: 1, lagrange_multiplier_of_T_variability: 0.02, lagrange_multiplier_of_X_variability: 0.1, lagrange_multiplier_of_Y_variability: 0.1}
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
            retrieved: true
            type: real_part_of_refractive_index_spectral_dependent
        characteristic[4]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1, 2, 3]
                    max: [0.1, 0.1, 0.1]
                    min: [1e-10, 1e-10, 1e-10]
                    value: [0.035, 0.035, 0.035]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
            retrieved: false
            type: imaginary_part_of_refractive_index_spectral_dependent
        characteristic[5]:
            type: surface_water_cox_munk_iso
            retrieved: false
            mode[1]:    
                initial_guess:                       #1      #2      #3      
                    value:                          [0.02,    0.013,   0.002  ]
                    min:                            [0.00000001,   0.00000001,  0.00000001 ]
                    max:                            [0.045,   0.035,   0.025 ]
                    index_of_wavelength_involved:   [1,      2,      3     ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 5.0e-2
            mode[2]:
                initial_guess:                       #1      #2      #3 
                    value:                          [0.999,   0.999,   0.999]
                    min:                             [0.998,   0.998,   0.998  ]
                    max:                            [1.0000, 1.0000, 1.0000 ]
                    index_of_wavelength_involved:   [1,      2,      3,]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 10.0e-0
            mode[3]:
                initial_guess:                       #1      #2      #3             
                    value:                          [0.033,    0.033,   0.033 ]  
                    min:                            [0.0015, 0.0015, 0.0015 ]
                    max:                            [0.1,    0.1,    0.1 ]
                    index_of_wavelength_involved:   [ 1,      2,      3 ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 10.0e2   
        characteristic[6]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:    [0.0000001]
                    value: [0.9999998]
                single_pixel:
                    smoothness_constraints: {difference_order: 0, lagrange_multiplier: 0.0}
            retrieved: false
            type: sphere_fraction
        characteristic[7]: 
            type: vertical_profile_parameter_height
            retrieved: false
            mode[1]:
                initial_guess:                      #1          
                    value:                          [1000.0 ]
                    min:                            [500.0] 
                    max:                            [5000.0]
                    index_of_wavelength_involved:   [0      ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0
            mode[2]:
                initial_guess:                      #1          
                    value:                          [1000.0 ]
                    min:                            [500.0] 
                    max:                            [5000.0]
                    index_of_wavelength_involved:   [0      ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0            
        characteristic[8]: 
            type: vertical_profile_parameter_standard_deviation
            retrieved: false
            mode[1]:
                initial_guess:                      #1          
                    value:                          [500.0 ]
                    min:                             [200.0  ] 
                    max:                            [2000.0 ]
                    index_of_wavelength_involved:   [0      ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0                                 
#        characteristic[8]:
#            mode[1]:
#                initial_guess:
#                    index_of_wavelength_involved: [1, 2, 3]
#                    max: [0.3383572, 0.5, 0.5]
#                    min: [0.338357, 0.1, 0.1]
#                    value: [0.338357150554657, 0.3, 0.3]
#                single_pixel:
#                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
#            mode[2]:
#                initial_guess:
#                    index_of_wavelength_involved: [1, 2, 3]
#                    max: [0.9, 0.9, 0.9]
#                    min: [0.0001, 0.0001, 0.0001]
#                    value: [0.43884894251823425, 0.5107452273368835, 0.5107452273368835]
#                single_pixel:
#                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
#            mode[3]:
#                initial_guess:
#                    index_of_wavelength_involved: [1, 2, 3]
#                    max: [0.9, 0.9, 0.9]
#                    min: [0.0001, 0.0001, 0.0001]
#                    value: [0.1366906464099884, 0.12526914477348328, 0.12526914477348328]
#                single_pixel:
#                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
#            retrieved: false
#            type: surface_land_brdf_ross_li
#        characteristic[9]:
#            mode[1]:
#                initial_guess:
#                    index_of_wavelength_involved: [1, 2, 3]
#                    max: [8.0, 8.0, 8.0]
#                    min: [1.0e-10, 1.0e-10, 1.0e-10]
#                    value: [2.0e-10, 2.0e-10, 2.0e-10]
#            retrieved: false
#            type: surface_land_polarized_maignan_breon            
    convergence: {maximum_iterations_for_stopping: 20, maximum_iterations_of_Levenberg-Marquardt: 20, minimization_convention: logarithm, normal_system_solver: sparse_matrix_solver, scale_for_finite_difference: 1.0e-03, shift_for_applying_logarithm_to_negative_values: 1.1, stop_before_performing_retrieval: true, threshold_for_stopping: 0.001, threshold_for_stopping_Q_iterations: 1.0e-05}
    debug: {additional_information: false, verbose: true}
    general: {path_to_internal_files: /usr/local/share/grasp/kernels/}
    noises:
        noise[1]:
            error_type: relative
            measurement_type[1]:
                index_of_wavelength_involved: [1, 2, 3]
                type: I
            standard_deviation: 0.03
            standard_deviation_synthetic: 0.0
        noise[2]:
            error_type: absolute
            measurement_type[1]:
                index_of_wavelength_involved: [1, 2, 3]
                type: Q
            measurement_type[2]:
                index_of_wavelength_involved: [1, 2, 3]
                type: U
            standard_deviation: 0.005
            standard_deviation_synthetic: 0.0
    phase_matrix:
        kernels_folder: KERNELS_BASE/
        number_of_elements: 4
        radius:
            mode[1]: {max: 15.0, min: 0.05}
        size_binning_method_for_triangle_bins: logarithm
    products:
        aerosol: {chemistry: false, lidar: true, optical_properties: true, particulate_matter: false, phase_matrix: false, refractive_index: true, theoretical_bimodal_extinction: false, theoretical_bimodal_parameters: true, type: false}
        error_estimation:
            aerosol: {lidar: false, optical_properties: false}
            parameters: false
        forcing: {broadband_flux: false, forcing: false}
        retrieval: {fitting: true, parameters: true, residual: true}
        surface: true
    radiative_transfer:
        absolute_error_rt_calculations: 1.0e-06
        aerosol_profile_vertical_type: exponential
        molecular_profile_vertical_type: exponential
        number_of_layers: 50
        reference_plane_for_polarization: principal_plane
        simulating_derivatives: {number_of_fourier_expansion_coefficients: 4, number_of_gaussian_quadratures_for_expansion_coefficients: 15, number_of_guassian_quadratures_for_fourier_expansion_coefficients: 4, order_of_scattering: derivatives}
        simulating_observation: {number_of_fourier_expansion_coefficients: 10, number_of_gaussian_quadratures_for_expansion_coefficients: 15, number_of_guassian_quadratures_for_fourier_expansion_coefficients: 20, order_of_scattering: multiple_scattering}
    regime_of_measurement_fitting: {polarization: absolute_polarization_components}
    regime_of_multipixel_constraints: {inversion_regime: single_pixel}
settings: {strict: true}
