input: {driver: sdata, file: bench.sdat}
output:
    segment: {function: classic, stream: bench_inversionRslts.txt}
retrieval:
    constraints:
        characteristic[1]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                    max: [2.0e-06, 2.0, 2.0, 2.0, 2.0, 2.0e-06, 2.0e-06, 2.0e-06, 2.0e-06, 2.0e-06] # top fine
                    min: [1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06]
                    value: [1.5e-06, 0.001, 0.001, 0.001, 0.001, 1.5e-06, 1.5e-06, 1.5e-06, 1.5e-06, 1.5e-06]
#                single_pixel:
#                    smoothness_constraints: {difference_order: 2, lagrange_multiplier: 1.0e-3}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                    max: [2.0e-06, 2.0, 2.0, 2.0, 2.0, 2.0e-06, 2.0e-06, 2.0e-06, 2.0e-06, 2.0e-06] # top coarse
                    min: [1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06]
                    value: [1.5e-06, 0.001, 0.001, 0.001, 0.001, 1.5e-06, 1.5e-06, 1.5e-06, 1.5e-06, 1.5e-06]
#                single_pixel:
#                    smoothness_constraints: {difference_order: 2, lagrange_multiplier: 1.0e-3}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                    max: [2.0e-06, 2.0e-06, 2.0e-06, 2.0e-06, 2.0e-06, 2.0, 2.0, 2.0, 2.0, 2.0e-06] # bottom fine
                    min: [1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06]
                    value: [1.5e-06, 1.5e-06,1.5e-06, 1.5e-06, 1.5e-06, 0.001, 0.001, 0.001, 0.001, 1.5e-06]
#                single_pixel:
#                    smoothness_constraints: {difference_order: 2, lagrange_multiplier: 1.0e-3}
            mode[4]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                    max: [2.0e-06, 2.0e-06, 2.0e-06, 2.0e-06, 2.0e-06, 2.0, 2.0, 2.0, 2.0, 2.0e-06] # bottom coarse
                    min: [1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06, 1.0e-06]
                    value: [1.5e-06, 1.5e-06,1.5e-06, 1.5e-06, 1.5e-06, 0.001, 0.001, 0.001, 0.001, 1.5e-06]
#                single_pixel:
#                    smoothness_constraints: {difference_order: 2, lagrange_multiplier: 1.0e-3}
            retrieved: true
            type: vertical_profile_normalized
        characteristic[2]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [0.25]
                    min: [0.00001]
                    value: [0.0002]
                single_pixel:
                    smoothness_constraints: {difference_order: 0, lagrange_multiplier: 0.0}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [0.25]
                    min: [0.00001]
                    value: [0.02]
                single_pixel:
                    smoothness_constraints: {difference_order: 0, lagrange_multiplier: 0.0}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [0.25]
                    min: [0.00001]
                    value: [0.0002]
                single_pixel:
                    smoothness_constraints: {difference_order: 0, lagrange_multiplier: 0.0}
            mode[4]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [0.25]
                    min: [0.00001]
                    value: [0.02]
                single_pixel:
                    smoothness_constraints: {difference_order: 0, lagrange_multiplier: 0.0}
            retrieved: true
            type: aerosol_concentration   
        characteristic[3]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [0.6, 0.75]
                    min: [0.15, 0.3] # case2 goes down to ~0.11 but this covers smoke, marine, pol, dust 
                    value: [0.17, 0.5]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier: [0, 0]                        
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [3.71, 0.77]
                    min: [0.7, 0.3]
                    value: [1.5, 0.5]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier: [0, 0]
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [0.6, 0.75]
                    min: [0.15, 0.3] # case2 goes down to ~0.11 but this covers smoke, marine, pol, dust 
                    value: [0.17, 0.5]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier: [0, 0]                        
            mode[4]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [3.71, 0.77]
                    min: [0.7, 0.3] 
                    value: [1.5, 0.5]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier: [0, 0]
            retrieved: true
            type: size_distribution_lognormal
        characteristic[4]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [1.65]
                    min: [1.35]
                    value: [1.363]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 1.0e5}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [1.52]
                    min: [1.35]
                    value: [1.363]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 1.0e5}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [1.65]
                    min: [1.35]
                    value: [1.363]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 1.0e5}
            mode[4]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [1.52]
                    min: [1.35]
                    value: [1.363]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 1.0e5}
            retrieved: true
            type: real_part_of_refractive_index_spectral_dependent
        characteristic[5]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [0.05]
                    min: [1e-5]
                    value: [0.001]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 1.0e5}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [0.03]
                    min: [1e-5]
                    value: [0.001]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 1.0e5}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [0.05]
                    min: [1e-5]
                    value: [0.001]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 1.0e5}
            mode[4]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [0.03]
                    min: [1e-5]
                    value: [0.001]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 1.0e5}
            retrieved: true
            type: imaginary_part_of_refractive_index_spectral_dependent            
        characteristic[6]:
            type: surface_water_cox_munk_iso
            retrieved: true
            mode[1]:    
                initial_guess:                       #1      #2      #3      
                    value:                          [0.000000002]
                    min:                             [0.000000001]
                    max:                            [0.00000002]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 1.0
            mode[2]:
                initial_guess:                       #1      #2      #3 
                    value:                          [0.9999]
                    min:                             [0.9998]
                    max:                            [1.0000]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 10.0e-0
            mode[3]:
                initial_guess:                       #1      #2      #3             
                    value:                          [0.01942]  
                    min:                             [0.0015]
                    max:                            [0.027]
                    index_of_wavelength_involved:   [ 1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 10.0e5
        characteristic[7]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:    [0.0000001]
                    value: [0.9999998]
                single_pixel:
                    smoothness_constraints: {difference_order: 0, lagrange_multiplier: 0.0}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:    [0.0000001]
                    value: [0.9999998]
                single_pixel:
                    smoothness_constraints: {difference_order: 0, lagrange_multiplier: 0.0}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:    [0.0000001]
                    value: [0.9999998]
                single_pixel:
                    smoothness_constraints: {difference_order: 0, lagrange_multiplier: 0.0}
            mode[4]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:    [0.0000001]
                    value: [0.9999998]
                single_pixel:
                    smoothness_constraints: {difference_order: 0, lagrange_multiplier: 0.0}
            retrieved: false
            type: sphere_fraction                        
#        characteristic[8]:
#            mode[1]:
#                initial_guess:
#                    index_of_wavelength_involved: [1]
#                    max: [0.3383572]
#                    min: [0.338357]
#                    value: [0.338357150554657]
#                single_pixel:
#                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
#            mode[2]:
#                initial_guess:
#                    index_of_wavelength_involved: [1]
#                    max: [0.9]
#                    min: [0.0001]
#                    value: [0.43884894251823425]
#                single_pixel:
#                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
#            mode[3]:
#                initial_guess:
#                    index_of_wavelength_involved: [1]
#                    max: [0.9]
#                    min: [0.0001]
#                    value: [0.1366906464099884]
#                single_pixel:
#                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
#            retrieved: false
#            type: surface_land_brdf_ross_li
#        characteristic[9]:
#            mode[1]:
#                initial_guess:
#                    index_of_wavelength_involved: [1]
#                    max: [8.0]
#                    min: [1.0e-10]
#                    value: [2.0e-10]
#            retrieved: false
#            type: surface_land_polarized_maignan_breon
    convergence: {maximum_iterations_for_stopping: 20, maximum_iterations_of_Levenberg-Marquardt: 20, minimization_convention: logarithm, normal_system_solver: sparse_matrix_solver, scale_for_finite_difference: 1.0e-03, shift_for_applying_logarithm_to_negative_values: 1.1, stop_before_performing_retrieval: false, threshold_for_stopping: 0.001, threshold_for_stopping_Q_iterations: 1.0e-12}
    debug: {additional_information: false, verbose: true}
    general: {path_to_internal_files: /usr/local/share/grasp/kernels/}
    noises:
        noise[1]:
            error_type: relative
            measurement_type[1]:
                index_of_wavelength_involved: [1]
                type: I
            standard_deviation: 0.03
            standard_deviation_synthetic: 0.0
        noise[2]:
            error_type: absolute
            measurement_type[1]:
                index_of_wavelength_involved: [1]
                type: Q
            measurement_type[2]:
                index_of_wavelength_involved: [1]
                type: U
            standard_deviation: 0.005
            standard_deviation_synthetic: 0.0            
        noise[3]:
            error_type: relative
            measurement_type[1]:
                index_of_wavelength_involved: [1]
                type: LS
            standard_deviation: 0.19
            standard_deviation_synthetic: 0.0
        noise[4]:
            error_type: absolute
            measurement_type[1]:
                index_of_wavelength_involved: [1]
                type: VEXT
#            standard_deviation: 0.05
            standard_deviation: 0.017e-03
            standard_deviation_synthetic: 0.0
        noise[5]:
            error_type: relative
            measurement_type[1]:
                index_of_wavelength_involved: [1]
                type: VBS
#            standard_deviation: 0.02
            standard_deviation: 0.1
#            standard_deviation: 0.43628e-06
            standard_deviation_synthetic: 0.0

    phase_matrix:
        kernels_folder: KERNELS_BASE/
        number_of_elements: 4
        radius:
            mode[1]: {max: 15.0, min: 0.05}
            mode[2]: {max: 15.0, min: 0.05}
            mode[3]: {max: 15.0, min: 0.05}
            mode[4]: {max: 15.0, min: 0.05}
        size_binning_method_for_triangle_bins: logarithm
    products:
        aerosol: {chemistry: false, lidar: true, optical_properties: true, particulate_matter: false, phase_matrix: true, refractive_index: true, theoretical_bimodal_extinction: false, theoretical_bimodal_parameters: true, type: false}
        error_estimation:
            aerosol: {lidar: false, optical_properties: false}
            parameters: false
        forcing: {broadband_flux: false, forcing: false}
        retrieval: {fitting: true, parameters: true, residual: true}
        surface: true
    radiative_transfer:
        absolute_error_rt_calculations: 1.0e-06
        aerosol_profile_vertical_type: exponential
        molecular_profile_vertical_type: exponential
        number_of_layers: 50
        reference_plane_for_polarization: principal_plane
        simulating_derivatives: {number_of_fourier_expansion_coefficients: 10, number_of_gaussian_quadratures_for_expansion_coefficients: 15, number_of_guassian_quadratures_for_fourier_expansion_coefficients: 20, order_of_scattering: derivatives}
        simulating_observation: {number_of_fourier_expansion_coefficients: 10, number_of_gaussian_quadratures_for_expansion_coefficients: 15, number_of_guassian_quadratures_for_fourier_expansion_coefficients: 20, order_of_scattering: multiple_scattering}
    regime_of_measurement_fitting: {polarization: relative_polarization_components}
    regime_of_multipixel_constraints: {inversion_regime: single_pixel}
settings: {strict: false}
