
input:
    driver: sdata
    file: fiveLambdaDummy.sdat

output:
    segment:
        function: classic
        stream: bench_inversionRslts.txt 
        
retrieval:
    general:
        path_to_internal_files: "/usr/local/share/grasp/kernels/"
#        path_to_internal_files: "/opt/grasp-0.8/share/grasp/kernels/"
        
    convergence:
        stop_before_performing_retrieval: false
        minimization_convention: logarithm
        threshold_for_stopping: 1.0e-3
        maximum_iterations_for_stopping: 20
        maximum_iterations_of_Levenberg-Marquardt: 20
        threshold_for_stopping_Q_iterations:  1.0e-5
        scale_for_finite_difference:          1.0e-3 
        normal_system_solver:       sparse_matrix_solver
        shift_for_applying_logarithm_to_negative_values: 1.1
        
    regime_of_measurement_fitting:
#        polarization: polarized_reflectance # P
#        polarization: linear_polarization # PoI
        polarization: absolute_polarization_components # Q, U
            
    regime_of_multipixel_constraints: 
        inversion_regime: single_pixel   

    noises:
        noise[1]:
            standard_deviation_synthetic: 0.0
            error_type:   relative
            standard_deviation:  0.03
            measurement_type[1]:
                type: I
                index_of_wavelength_involved: [ 1,2,3,4,5]
        noise[2]:
            standard_deviation_synthetic: 0.0
            error_type:  absolute
            standard_deviation:  0.005
            measurement_type[1]:
                type: Q
                index_of_wavelength_involved: [ 1, 2, 3, 4, 5]
            measurement_type[2]:
                type: U
                index_of_wavelength_involved: [ 1, 2, 3, 4, 5 ]

    radiative_transfer:
        number_of_layers: 50 #50 -> 100, no meaningful improvement
        aerosol_profile_vertical_type:    exponential
        molecular_profile_vertical_type:   exponential 
#        molecular_profile_vertical_type:   no_rayleigh 
        absolute_error_rt_calculations: 0.000001 # this helps, at least once quadratures_for_fourier_expansion is sufficiently high, max of default allowed range
#        reference_plane_for_polarization:   meridian
        reference_plane_for_polarization:   principal_plane
        simulating_observation:
#            order_of_scattering: single_scattering
            order_of_scattering: multiple_scattering
            number_of_gaussian_quadratures_for_expansion_coefficients:  4 # 41 is max, this should have no effect w/o aerosol
            number_of_guassian_quadratures_for_fourier_expansion_coefficients:  50 # big diff here, diminishing returns after 20 though
            number_of_fourier_expansion_coefficients:  10 # 4->10 makes very little difference in BRDF+BPDF case, nothing after that
        simulating_derivatives:
            order_of_scattering: derivatives
            number_of_gaussian_quadratures_for_expansion_coefficients:  15
            number_of_guassian_quadratures_for_fourier_expansion_coefficients:   4
            number_of_fourier_expansion_coefficients:   4

    phase_matrix:
        size_binning_method_for_triangle_bins: logarithm
        number_of_elements: 4
        kernels_folder: "KERNELS_BASE/"
        radius:
            mode[1]:
                min: 0.05
                max: 15.0
            mode[2]:
                min: 0.05
                max: 15.0

 
    products:                   
        aerosol:
            chemistry: false
            lidar: false                            
            optical_properties: true                
            phase_matrix: false                      
            refractive_index: true                 
            theoretical_bimodal_extinction: false    
            theoretical_bimodal_parameters: true  
            particulate_matter: false
            type: false
        error_estimation:
            aerosol:
                lidar: false            
                optical_properties: false
            parameters: false               
        forcing:
            broadband_flux: false                    
            forcing: false                           
        retrieval:
            fitting: true                       
            parameters: true                      
            residual: true                        
        surface: true                                   

    debug:
        additional_information: false
        verbose: true

    constraints:                            
        characteristic[1]: 
            type: aerosol_concentration
            retrieved: true
            mode[1]: 
                initial_guess: 
                    value:                        [0.05]
                    min:                          [0.0015]
                    max:                          [2.000]
                    index_of_wavelength_involved: [0]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0
            mode[2]: 
                initial_guess: 
                    value:                        [0.05]
                    min:                          [0.0015]
                    max:                          [2.000]
                    index_of_wavelength_involved: [0]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0

        characteristic[2]: 
            type: size_distribution_lognormal
            retrieved: true
            mode[1]: 
                initial_guess: 
                    value:                        [0.2,       0.5]
                    min:                           [0.05,       0.3]
                    max:                          [1.00,       0.8]
                    index_of_wavelength_involved: [0,     0]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier:      [0,  0]
            mode[2]: 
                initial_guess: 
                    value:                        [3.0,   0.5]
                    min:                           [1.0,   0.3] 
                    max:                          [6.0,  0.8]
                    index_of_wavelength_involved: [0,     0]
                single_pixel:
                    a_priori_estimates:
                        lagrange_multiplier:      [0,  0]
                        
        characteristic[3]:
            type: real_part_of_refractive_index_spectral_dependent
            retrieved: true
            mode[1]:
                initial_guess:                       #1         #2        #3        #4        #5        #6       
                    value:                         [1.4, 1.4, 1.4, 1.4, 1.4]
                    min:                            [1.33,1.33,1.33,1.33,1.33]
                    max:                            [1.6,1.6,1.6,1.6,1.6]
                    index_of_wavelength_involved:   [1,2,3,4,5] 
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0
            mode[2]:
                initial_guess:                       #1         #2        #3        #4        #5        #6       
                    value:                         [1.4, 1.4, 1.4, 1.4, 1.4]
                    min:                            [1.33,1.33,1.33,1.33,1.33]
                    max:                            [1.6,1.6,1.6,1.6,1.6]
                    index_of_wavelength_involved:   [1,2,3,4,5] 
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0
                                                                       
        characteristic[4]:
            type: imaginary_part_of_refractive_index_spectral_dependent
            retrieved: true
            mode[1]:
                initial_guess:                       #1        #2        #3        #4        #5        #6    
                    value:                          1.0e-5, 1.0e-5, 1.0e-5, 1.0e-5, 1.0e-5]
                    min:                            [1e-10, 1e-10, 1e-10, 1e-10, 1e-10,]
                    max:                            [0.1, 0.1, 0.1, 0.1, 0.1]
                    index_of_wavelength_involved:   [1,2,3,4,5]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0
            mode[2]:
                initial_guess:                       #1        #2        #3        #4        #5        #6    
                    value:                          1.0e-5, 1.0e-5, 1.0e-5, 1.0e-5, 1.0e-5]
                    min:                            [1e-10, 1e-10, 1e-10, 1e-10, 1e-10,]
                    max:                            [0.1, 0.1, 0.1, 0.1, 0.1]
                    index_of_wavelength_involved:   [1,2,3,4,5]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0

        characteristic[5]: 
            type: surface_land_brdf_ross_li # NEEDS TO GO ABOVE BPDF
            retrieved: false
            mode[1]:    #ISO
                initial_guess:                       #1     #2     #3     #4     #5     #6 wvls = [0.410]
                    value:                          [0.000000000001, 0.000000000001, 0.000000000001, 0.000000000001, 0.000000000001]     
                    min:                             [0.00000000000001, 0.00000000000001, 0.00000000000001, 0.00000000000001, 0.00000000000001]
                    max:                            [0.9, 0.9, 0.9, 0.9, 0.9]
                    index_of_wavelength_involved:   [1,2,3,4,5] 
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0

            mode[2]:  # VOL
                initial_guess:                       #1     #2     #3     #4     #5     #6
                    value:                          [0.5107452273368835, 0.5107452273368835, 0.5107452273368835, 0.5107452273368835, 0.5107452273368835]    
                    min:                            [0.510745, 0.01, 0.01, 0.01, 0.01]
                    max:                            [0.5107453, 1.0,  1.0,  1.0,  1.0]
                    index_of_wavelength_involved:   [1,2,3,4,5] 
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0
                       
            mode[3]:  #GEOM
                initial_guess:                       #1     #2     #3     #4     #5     #6       
                    value:                          [0.12526914477348328, 0.1, 0.1, 0.1, 0.1]
                    min:                            [0.01, 0.01, 0.01, 0.01, 0.01]
                    max:                            [0.9, 0.9, 0.9, 0.9, 0.9]
                    index_of_wavelength_involved:   [1,2,3,4,5] 
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0

        characteristic[6]: 
            type: sphere_fraction
            retrieved: false
            mode[1]:
                initial_guess:                      #1      
                    value:                          [0.9999998 ]
                    min:                            [0.9999997 ]
                    max:                            [0.9999999]
                    index_of_wavelength_involved:   [0     ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0
            mode[2]:
                initial_guess:                      #1      
                    value:                          [0.9999998 ]
                    min:                            [0.9999997 ]
                    max:                            [0.9999999]
                    index_of_wavelength_involved:   [0     ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0

        characteristic[7]: 
            type: vertical_profile_parameter_height
            retrieved: false
            mode[1]:
                initial_guess:                      #1          
                    value:                          [1000.0 ]
                    min:                            [10.0   ] 
                    max:                            [10000.0 ]
                    index_of_wavelength_involved:   [0      ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0
            mode[2]:
                initial_guess:                      #1          
                    value:                          [1000.0 ]
                    min:                            [10.0   ] 
                    max:                            [10000.0 ]
                    index_of_wavelength_involved:   [0      ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0
                         
settings:
   strict: true

