input: {driver: sdata, file: inversionBACK.sdat}
output:
    segment: {function: classic, stream: bench_inversionRslts.txt}
retrieval:
    constraints:
        characteristic[1]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [0.15]
                    min: [0.00000001]
                    value: [0.001]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [0.09]
                    min: [0.00000001]
                    value: [0.002]
            retrieved: true
            type: aerosol_concentration    
        characteristic[2]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1] 
                    max: [0.04]
                    min: [1e-3]
                    value: [0.005]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.5
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [0.04]
                    min: [1e-3]
                    value: [0.005]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.5
            retrieved: true
            type: imaginary_part_of_refractive_index_spectral_dependent
        characteristic[3]: 
            type: vertical_profile_parameter_height
            retrieved: false
            mode[1]:
                initial_guess:                      #1          
                    value:                          [3000.0 ]
                    min:                            [2500.0] 
                    max:                            [3500.0]
                    index_of_wavelength_involved:   [0      ]
            mode[2]:
                initial_guess:                      #1          
                    value:                          [3000.0 ]
                    min:                            [2500.0] 
                    max:                            [3500.0]
                    index_of_wavelength_involved:   [0      ]
        characteristic[4]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [0.34, 0.70]
                    min: [0.07, 0.25]
                    value: [0.13776, 0.38912]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [6.0, 0.8]
                    min: [0.65, 0.25]
                    value: [3.669, 0.6254]
            retrieved: false
            type: size_distribution_lognormal
        characteristic[5]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [  1.49,       1.49,       1.50,       1.51,       1.52,      1.52,      1.52]
                    min: [  1.47,       1.47,       1.48,       1.49,       1.50,      1.50,      1.50]
                    value: [1.47497788, 1.47867788, 1.48855341, 1.50089341, 1.51197788, 1.51297788, 1.51297788]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.5
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [  1.49,       1.49,       1.50,       1.51,       1.52,      1.52,      1.52]
                    min: [  1.47,       1.47,       1.48,       1.49,       1.50,      1.50,      1.50]
                    value: [1.47497788, 1.47867788, 1.48855341, 1.50089341, 1.51197788, 1.51297788, 1.51297788]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.5
            retrieved: false
            type: real_part_of_refractive_index_spectral_dependent
#        VEGITATION INSPIRED 
        characteristic[6]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1] # λ=[0.415, 0.470, 0.555, 0.659, 0.865, 1.64, 2.13] μm
                    max:                               [0.2,     0.2,    0.2,      0.5,      0.6,      1.5,    1.5]
                    min:                               [0.0005, 0.0005, 0.0005,   0.0005,   0.0500,   0.0250, 0.020]
                    value:                             [0.0237, 0.0368, 0.072282, 0.057601, 0.42234,  0.2457, 0.1128]
                single_pixel:
                    smoothness_constraints: {difference_order: 2, lagrange_multiplier: 0}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max:   [2.0 ]
                    min:   [0.001]
                    value: [0.6073 ]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 10}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max:   [1.0]
                    min:   [0.0001]
                    value: [0.1411]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 10}
            retrieved: false
            type: surface_land_brdf_ross_li
        characteristic[7]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:   [0.6000000]
                    value: [0.9999998]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:    [0.0000001]
                    value: [0.9999998]
            retrieved: false
            type: sphere_fraction
        characteristic[8]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max:   [0.000003]
                    min:   [0.000001]
                    value: [0.000002]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 10}
            retrieved: false
            type: surface_land_polarized_maignan_breon
        characteristic[9]: 
            type: vertical_profile_parameter_standard_deviation
            retrieved: false
            mode[1]:
                initial_guess:                      #1          
                    value:                          [500.0 ]
                    min:                            [200.0  ] 
                    max:                            [3000.0 ]
                    index_of_wavelength_involved:   [0      ]
            mode[2]:
                initial_guess:                      #1          
                    value:                          [500.0 ]
                    min:                            [200.0  ] 
                    max:                            [3000.0 ]
                    index_of_wavelength_involved:   [0      ]
        characteristic[10]:
            type: surface_water_CxMnk_iso_noPol
            retrieved: false
            mode[1]:    
                initial_guess:                       #1      #2      #3      
                    value:                          [0.000000002]
                    min:                            [0.000000001]
                    max:                            [0.000000003]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.0
            mode[2]:
                initial_guess:                       #1      #2      #3 
                    value:                          [0.999999]
                    min:                            [0.999998]
                    max:                            [1.000000]
                    index_of_wavelength_involved:   [0]
            mode[3]:
                initial_guess:                       #1      #2      #3             
                    value:                          [0.015]  
                    min:                            [0.00406] # 1 m/s
                    max:                            [0.040] # 0.027 -> 10 m/s
                    index_of_wavelength_involved:   [0]

    convergence: 
        maximum_iterations_for_stopping: 40
        maximum_iterations_of_Levenberg-Marquardt: 40
        minimization_convention: logarithm
        normal_system_solver: sparse_matrix_solver
        scale_for_finite_difference: 1.0e-05 #2.0e-5
        shift_for_applying_logarithm_to_negative_values: 1.1
        threshold_for_stopping: 1.0e-9 #0.001
        threshold_for_stopping_Q_iterations: 1.0e-09 #1.0e-06
        stop_before_performing_retrieval: false
    debug: {additional_information: false, verbose: true}
    general: {path_to_internal_files: /usr/local/share/grasp/kernels/}
    noises:
        noise[1]:
            error_type: relative
            measurement_type[1]:
                index_of_wavelength_involved: [1]
                type: I
            standard_deviation: 0.03
            standard_deviation_synthetic: 0.0
    phase_matrix:
        kernels_folder: KERNELS_BASE/
        number_of_elements: 4
        radius:
            mode[1]: {max: 15.0, min: 0.05}
            mode[2]: {max: 15.0, min: 0.05}
        size_binning_method_for_triangle_bins: logarithm
    products:
        aerosol: {chemistry: false, lidar: true, optical_properties: true, particulate_matter: false, phase_matrix: false, refractive_index: true, theoretical_bimodal_extinction: false, theoretical_bimodal_parameters: true, type: false}
        error_estimation:
            aerosol: {lidar: false, optical_properties: false}
            parameters: false
        forcing: {broadband_flux: false, forcing: false}
        retrieval: {fitting: true, parameters: true, residual: true}
        surface: true
    radiative_transfer:
        absolute_error_rt_calculations: 1.0e-06
        aerosol_profile_vertical_type: gaussian
        molecular_profile_vertical_type: exponential
        number_of_layers: 50
        reference_plane_for_polarization: meridian
        simulating_derivatives:
            number_of_fourier_expansion_coefficients: 6
            number_of_gaussian_quadratures_for_expansion_coefficients: 10
            number_of_guassian_quadratures_for_fourier_expansion_coefficients: 20
            order_of_scattering: derivatives
        simulating_observation:
            number_of_fourier_expansion_coefficients: 6
            number_of_gaussian_quadratures_for_expansion_coefficients: 10
            number_of_guassian_quadratures_for_fourier_expansion_coefficients: 20
            order_of_scattering: multiple_scattering
    regime_of_measurement_fitting: {polarization: relative_polarization_components}
    regime_of_multipixel_constraints: {inversion_regime: single_pixel}
settings: {strict: true}
