
input:
    driver: sdata
    file: bench.sdat


output:
    segment:
        function: classic
        stream: bench_inversionRslts.txt 
        
retrieval:
    general:
        path_to_internal_files: "/usr/local/share/grasp/kernels/"
#        path_to_internal_files: "/opt/grasp-0.8/share/grasp/kernels/"
        
    convergence:
        stop_before_performing_retrieval: true
        minimization_convention: logarithm
        threshold_for_stopping: 1.0e-3
        maximum_iterations_for_stopping: 20
        maximum_iterations_of_Levenberg-Marquardt: 20
        threshold_for_stopping_Q_iterations:  1.0e-5
        scale_for_finite_difference:          1.0e-3 
        normal_system_solver:       sparse_matrix_solver
        shift_for_applying_logarithm_to_negative_values: 1.1
        
    regime_of_measurement_fitting:
#        polarization: polarized_reflectance # P
#        polarization: degree_of_polarization # PoI [CHANGED FROM linear_polarization IN V0.8.1]
        polarization: absolute_polarization_components # Q, U
            
    regime_of_multipixel_constraints: 
        inversion_regime: single_pixel   

    noises:
        noise[1]:
            standard_deviation_synthetic: 0.0
            error_type:   relative
            standard_deviation:  0.03
            measurement_type[1]:
                type: I
                index_of_wavelength_involved: [ 1]
        noise[2]:
            standard_deviation_synthetic: 0.0
            error_type:  absolute
            standard_deviation:  0.005
            measurement_type[1]:
                type: Q
                index_of_wavelength_involved: [ 1]
            measurement_type[2]:
                type: U
                index_of_wavelength_involved: [ 1]

    radiative_transfer:
        number_of_layers: 50 #50 -> 100, no meaningful improvement
        aerosol_profile_vertical_type:    exponential
        molecular_profile_vertical_type:   exponential 
#        molecular_profile_vertical_type:   no_rayleigh 
        absolute_error_rt_calculations: 0.000001 # this helps, at least once quadratures_for_fourier_expansion is sufficiently high, max of default allowed range
#        reference_plane_for_polarization:   meridian
        reference_plane_for_polarization:   principal_plane
        simulating_observation:
#            order_of_scattering: single_scattering
            order_of_scattering: multiple_scattering
            number_of_gaussian_quadratures_for_expansion_coefficients:  20 # 41 is max, this should have no effect w/o aerosol
            number_of_guassian_quadratures_for_fourier_expansion_coefficients:  50 # big diff here, diminishing returns after 20 though
            number_of_fourier_expansion_coefficients:  10 # 4->10 makes very little difference in BRDF+BPDF case, nothing after that
        simulating_derivatives:
            order_of_scattering: derivatives
            number_of_gaussian_quadratures_for_expansion_coefficients:  15
            number_of_guassian_quadratures_for_fourier_expansion_coefficients:   4
            number_of_fourier_expansion_coefficients:   4

    phase_matrix:
        size_binning_method_for_triangle_bins: logarithm
        number_of_elements: 4
        kernels_folder: "KERNELS_BASE/"
        radius:
            mode[1]:
                min: 0.05
                max: 0.6
 
#    product_configuration:
#        wavelength_indices_for_angstrom: [4, 5]
#        wavelength_indices_for_ndvi: [4, 5]

    products:                   
        aerosol:
            chemistry: false
            lidar: false                            
            optical_properties: true                
            phase_matrix: false                      
            refractive_index: true                 
            theoretical_bimodal_extinction: false    
            theoretical_bimodal_parameters: true  
            particulate_matter: false
            type: false
        error_estimation:
            aerosol:
                lidar: false            
                optical_properties: false
            parameters: false               
        forcing:
            broadband_flux: false                    
            forcing: false                           
        retrieval:
            fitting: true                       
            parameters: true                      
            residual: true                        
        surface: true                                   

    debug:
        additional_information: false
        verbose: true

    constraints:    
        characteristic[1]:
            type: surface_water_cox_munk_iso
            retrieved: true
            mode[1]:    
                initial_guess:                       #1      #2      #3      #4      #5      #6       
                    value:                          [0.00000000000000001]
                    min:                             [0.000000000000000001]
                    max:                            [0.05]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 1.0e-3
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    1
                       lagrange_multiplier_of_X_variability: 1.0e-3                        
                       derivative_order_of_Y_variability:    1
                       lagrange_multiplier_of_Y_variability: 1.0e-3
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 1.0e-3

            mode[2]:
                initial_guess:                       #1      #2      #3      #4      #5      #6       
                    value:                          [0.9999999999999999999999]
                    min:                             [0.60]
                    max:                            [1.0000]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 10.0e-0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    1
                       lagrange_multiplier_of_X_variability: 1.0e-3                        
                       derivative_order_of_Y_variability:    1
                       lagrange_multiplier_of_Y_variability: 1.0e-3
                       derivative_order_of_T_variability:    0
                       lagrange_multiplier_of_T_variability: 1.0e-3

            mode[3]:
                initial_guess:                       #1      #2      #3      #4      #5      #6       
                    value:                          [0.0143]
                    min:                            [0.0015]
                    max:                            [0.1]
                    index_of_wavelength_involved:   [ 1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 10.0e-0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    1
                       lagrange_multiplier_of_X_variability: 1.0e-3                        
                       derivative_order_of_Y_variability:    1
                       lagrange_multiplier_of_Y_variability: 1.0e-3
                       derivative_order_of_T_variability:    0
                       lagrange_multiplier_of_T_variability: 1.0e-3

        characteristic[2]: 
            type: surface_land_brdf_ross_li # NEEDS TO GO ABOVE BPDF
            retrieved: true
            mode[1]:    #ISO
                initial_guess:                       #1     #2     #3     #4     #5     #6 wvls = [0.410]
#                    value:                          [0.000000000001]     
#                    min:                             [0.00000000000001]
#                    max:                            [0.9]
                    value:                          [0.338357150554657]     
                    min:                             [0.338357]
                    max:                            [0.3383572]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    0
                       lagrange_multiplier_of_X_variability: 1.0e-3                        
                       derivative_order_of_Y_variability:    0
                       lagrange_multiplier_of_Y_variability: 1.0e-3
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 1.0e-0                            

            mode[2]:  # VOL
                initial_guess:                       #1     #2     #3     #4     #5     #6
                    value:                          [0.5107452273368835]    
                    min:                            [0.510745]
                    max:                            [0.5107453]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    0
                       lagrange_multiplier_of_X_variability: 1.0e-3                        
                       derivative_order_of_Y_variability:    0
                       lagrange_multiplier_of_Y_variability: 1.0e-3
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 1.0e-0
                       
            mode[3]:  #GEOM
                initial_guess:                       #1     #2     #3     #4     #5     #6       
                    value:                          [0.12526914477348328]
                    min:                            [0.125269]
                    max:                            [0.1252692]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    0
                       lagrange_multiplier_of_X_variability: 1.0e-3                        
                       derivative_order_of_Y_variability:    0
                       lagrange_multiplier_of_Y_variability: 1.0e-3
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 1.0e-0                            

        characteristic[3]:
            type: surface_land_polarized_maignan_breon
            retrieved: true
            mode[1]: 
                initial_guess:                       #1        #2        #3        #4        #5        #6        
                    value:                          [0.0000000002]
                    min:                             [0.0000000001]
                    max:                            [8.0]
#                    value:                          [5.3208382787]
#                    min:                            [1.5]
#                    max:                            [8.0]
                    index_of_wavelength_involved:   [1]

        characteristic[4]:
            type: real_part_of_refractive_index_spectral_dependent
            retrieved: false
            mode[1]:
                initial_guess:                       #1         #2        #3        #4        #5        #6       
                    value:                          [1.3311057]
                    min:                            [1.33]
                    max:                            [1.6]
                    index_of_wavelength_involved:   [1] 
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    1
                       lagrange_multiplier_of_X_variability: 1.0e-1                        
                       derivative_order_of_Y_variability:    1
                       lagrange_multiplier_of_Y_variability: 1.0e-1                     
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 2.0e-2                                               
                       
        characteristic[5]: 
            type: size_distribution_triangle_bins
            retrieved: false
            mode[1]: 
                initial_guess:                         #1         #2        #3        #4        #5        #6        #7        #8        #9        #10       #11       #12       #13       #14       #15       #16       
                      value:                            [0.0000000000002,  0.0000000000002, 0.0000000000002, 0.0000000000002, 0.0000000000002, 0.0000000000002, 0.0000000000002, 0.0000000000002, 0.0000000000002, 0.0000000000002, 0.0000000000002, 0.0000000000002, 0.0000000000002, 0.0000000000002, 0.0000000000002, 0.0000000000002  ]
                      min:                               [0.0000000000001,   0.0000000000001, 0.0000000000001, 0.0000000000001, 0.0000000000001, 0.0000000000001, 0.0000000000001, 0.0000000000001, 0.0000000000001, 0.0000000000001, 0.0000000000001, 0.0000000000001, 0.0000000000001, 0.0000000000001, 0.0000000000001, 0.0000000000001  ]
                      max:                            [5.0,       15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     15.0,     5.0       ]
                      index_of_wavelength_involved:   [0,         0,        0,        0,        0,        0,        0,        0 ,       0,        0,        0,        0,        0,        0,        0,        0         ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    1
                       lagrange_multiplier_of_X_variability: 1.0e-1                        
                       derivative_order_of_Y_variability:    1
                       lagrange_multiplier_of_Y_variability: 1.0e-1                     
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 5.0e-4
                                                
        characteristic[6]:
            type: imaginary_part_of_refractive_index_spectral_dependent
            retrieved: false
            mode[1]:
                initial_guess:                       #1        #2        #3        #4        #5        #6    
                    value:                          [4.446029e-09]
                    min:                            [1e-10]
                    max:                            [0.1]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    1
                       lagrange_multiplier_of_X_variability: 1.0e-1                        
                       derivative_order_of_Y_variability:    1
                       lagrange_multiplier_of_Y_variability: 1.0e-1                     
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 2.0e-2

        characteristic[7]: 
            type: sphere_fraction
            retrieved: false
            mode[1]:
                initial_guess:                      #1      
                    value:                          [0.9999998   ]
                    min:                            [0.9999997 ]
                    max:                            [0.9999999]
                    index_of_wavelength_involved:   [0     ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0.0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    1
                       lagrange_multiplier_of_X_variability: 1.0e-1                        
                       derivative_order_of_Y_variability:    1
                       lagrange_multiplier_of_Y_variability: 1.0e-1                     
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 1.0e-2

        characteristic[8]: 
            type: vertical_profile_parameter_height
            retrieved: false
            mode[1]:
                initial_guess:                      #1          
                    value:                          [1635.7 ]
                    min:                            [10.0   ] 
                    max:                            [10000.0 ]
                    index_of_wavelength_involved:   [0      ]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 0
                        lagrange_multiplier: 0
                multi_pixel:
                   smoothness_constraints:
                       derivative_order_of_X_variability:    1
                       lagrange_multiplier_of_X_variability: 1.0e-1                        
                       derivative_order_of_Y_variability:    1
                       lagrange_multiplier_of_Y_variability: 1.0e-1                     
                       derivative_order_of_T_variability:    1
                       lagrange_multiplier_of_T_variability: 1.0e-2
                         
settings:
   strict: true

